language: objective-c
osx_image: xcode9.3beta
# xcode_workspace: SimpleTodo.xcworkspace
# xcode_scheme: SimpleTodo
# xcode_sdk: iphonesimulator11.0
branches:
  only:
    - develop
    - master
env:
  - LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8
# before_install:
#   - rvm install ruby-2.2.2
#   - gem install cocoapods
#   - gem install xcpretty -N
#   - brew update
#   - brew install swiftlint || true
 script:
   - set -o pipefail
   - xcodebuild clean build -sdk iphonesimulator -workspace SimpleTodo.xcworkspace -scheme SimpleTodo CODE_SIGNING_REQUIRED=NO
  #  - swiftlint