language: swift
osx_image: xcode14
xcode_workspace: SimpleTodo.xcworkspace
xcode_project: SimpleTodo.xcodeproj # path to your xcodeproj folder
xcode_scheme: SimpleTodo
xcode_destination: platform=iOS Simulator,OS=11.3,name=iPhone X
before_install:
- gem install cocoapods
- pod install
branches:
  only:
  - develop
  - master
env:
- LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8
# script:
# - set -o pipefail
# - xcodebuild clean build -sdk iphonesimulator -workspace SimpleTodo.xcworkspace -scheme SimpleTodo CODE_SIGNING_REQUIRED=NO