language: objective-c
osx_image: xcode9.3beta
branches:
  only:
    - develop
    - master
env:
  - LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8
 script:
   - set -o pipefail
   - xcodebuild clean build -sdk iphonesimulator -workspace SimpleTodo.xcworkspace -scheme SimpleTodo CODE_SIGNING_REQUIRED=NO