# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :build do
    # add actions here: https://docs.fastlane.tools/actions
    gym(
      workspace: "SimpleTodo.xcworkspace", 
      scheme: "SimpleTodo",
      clean: true
    )
  end

  lane :test do
    scan(
      workspace: "SimpleTodo.xcworkspace", 
      scheme: "SimpleTodo",
      devices: ["iPhone 8 (14.4)", "iPad Pro (9.7-inch)"],
      clean: true
    )
  end
end
